import React from "react";
import Seo from "../components/Seo";
import Layout from "../components/structure/Layout";
import Container from "../components/structure/Container";
import "../styles/styles.scss"

const HistoryPage = () => (
    <Layout>
        <Seo title="History" />
        <article>
            <Container>
                <section>
                    <h1>History</h1>
                    <div className="content__header">
                        <h2>How the IATD Came To Be</h2>
                        <p><em>Written by John S. Pratt, President &amp; Founder</em></p>
                    </div>
                    <p>The forming of a body of "Traditional" drummers to establish standards for performance excellence is not a new idea. It was first conceived in response to dealing with a lack of uniformity in judging American Legion and VFW drum and bugle corps contests on a national scale, which also included contests in individual drumming. "Running down" the long roll provided a good example of this need for uniformity since the two standard drum books in use in the 1920's and early 1930's were the Bruce and Emmett and the Strube books, both of which differed in their ideas as to how the long roll should be performed. Bruce and Emmett advocated that an accent be placed on the roll's second beat when starting it and called for a de-acceleration of the roll after it had reached maximum speed. Strube, on the other hand, did not advocate either of these requirements. Such discrepancies obviously could not be tolerated for long, and one of the outcomes that resulted from inconsistent scoring by the various individuals who had been judging drum and bugle corps contests and individual competitions, was that a group of drummers got together on June 20, 1933 at the American Legion National Convention in Chicago and organized a group known as The National Assocation of Rudimental Drummers, who in turn adopted the 26 Standard American Drum Rudiments. William F. Ludwig later recalled that the group "retained the Bruce and Emmett roll, open and closed [and] also retain lesson #25 of the Strube method. We divided the 26 rudiments into two sections by selecting, what we termed at the time, the 13 essential [rudiments] that each applicant had to play as a test for membership into the National Association of Rudimental Drummers"</p>
                    <p>A list of the 13 leading percussionists, who participated in founding the NARD, included the following: J. Burns Moore, Bill Kieffer, Bill Hammond, George Lawrence Stone, Joe Hathaway, William F. Ludwig, Heinie Gerlach, Roy Knapp, Bill Flowers, Harry Thompson, George A Robertson, Billy Miller, and Ed Straight.</p>
                    <p>It is important to note that these men and others like them believed in the traditions that had been handed down to them historically and were interested in preserving those traditions for future generations by adopting a set of standards as to what rudimental configurations were worthwhile establishing. In the last several decades, however, there have been additions to the standard drumming rudiments established by NARD. The Percussive Arts Society of America, for example, decided to expand the number of drumming rudiments to 40, by adding a number of rudiments to the original 26. They entitled their list "Percussive Arts Society International Rudiments" and among these rudiments were a number of rudiments from the Swiss "Traditional" configurations such as the Single Flammed Mill stroke, the Pataflafla, ths Swiss Army Triplet and the Swiss Tap Flam, which the PAS called the "Inverted Flam Tap" In addition, they cast aside the designation of the "Traditional" American Rudiment known as the "Ruff" renaming it as a "Drag" and came up with new configurations such as the "Flam Drag", the "Single Drag Tap", and the "Double Drag Tap" (both with changed basic rhythms from the NARD's traditional system). Finally they also listed a "Single Dragadiddle". All such changes are obvious departures from the "Traditional" configurations of the 26 Standard American Rudiments adopted by the NARD in 1933.</p>
                    <p>Obviously, the goal of The International Association of Traditional Drummers is, in a sense, similar to that of the NARD's in the 20th Century, and we have formed our group with one purpose: to preserve our own country's drumming traditions, while also respecting the traditions of other countries. By so doing, we can enjoy one brotherhood of drummers around the world without borrowing from their traditions and trying to make them part of our own. As my teacher, Norman H. Peth, has argued, "if a drumming system is considered to be 'Traditional', then it cannot contain a confusion of drumming patterns or techniques."</p>    
                    <p>Why is "Traditional" rudimental drumming still valuable today? Because it's always fresh; it has timeless technical benefits for a drummer's control and development, especially of the left hand, and it has great musical value in its unique technical phrasing with its rudimental constructions and accents. IATD's purpose is to make drummers aware that they should add the "logs" of "Traditional" drumming to their developmental fires to fuel the growth of their drumming knowledge, especially if they have not grown up with the "Traditional" drumming system, where playing a drum solo for sheer enjoyment was accepted rather than a field drummer being regarded as just a minor cog in a musically-oriented marching performance. "Traditional" drumming was and still is an ART FORM. Therefore, drummers all need to understand that they are part of this greater tradition, and should expose themselves to it.</p>    
                    <p>Why is the preservation of Traditional drumming worthwile? It is because most drummers, whether they know it or not, have developed from its roots in the past, and need to be made aware of its value, especially today. There is a gold-mine of rhythmic wealth just waiting to be discovered by today's percussionists to aid them in filling in the technical (rudimental) gaps in their drumming education and/or their acquired knowledge.</p>    
                    <p>In order to get our program organized and under way, a number of Master Drummers will be recognized in the USA, Canada, Scotland, Switzerland, England, Finland, Australia, Japan and in other nations around the world. They, in turn, will act as representatives for the International Association of Traditional Drummers and will be given authority as IATD examining judges so that students that they may have can be screened and tested for membership according to the Traditional standards of their particular countries.</p>    
                    <p>Finally, the certificates to be awarded to the Master Drummers will have Gold Borders, and their students and other applicants for membership, who have been approved by testing, will receive Blue Bordered certificates. Last but not least, since the certificates awarded by NARD had green borders, we thought it was appropriate that there would also be green borders on the certificates of our honorary charter members: Norman H Peth, John S Pratt, Kenneth H Green, Vincent J Czepiel, and Thomas M Sorenson.</p>
                </section>
            </Container>
        </article>
    </Layout>
)

export default HistoryPage;
